stages:
  - deploy

deploy_to_github:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    - echo "Setting Git configuration..."
    - git config --global http.postBuffer 524288000   # Increase Git buffer size to 500MB
    - git config --global user.email "nguyenngocbinhneu@gmail.com"
    - git config --global user.name "Nguyen Ngoc Binh"
    - echo "Cloning repository..."
    - git clone --mirror https://oauth2:$GITLAB_PERSONAL_ACCESS_TOKEN@gitlab.com/nguyenngocbinh/snippets.git || (echo "Clone failed"; exit 1)
    - cd snippets.git
    - echo "Adding GitHub remote..."
    - git remote add github https://$GITHUB_TOKEN@github.com/nguyenngocbinh/snippets.git
    - echo "Pushing to GitHub..."
    - git push --mirror github || (echo "Push failed"; exit 1)
  only:
    - main