project: 
  type: website
  
website: 
  page-navigation: true
  title: "Snippets " 
  site-url: "https://nguyenngocbinh.github.io/snippets" 
  repo-url: https://github.com/nguyenngocbinh/snippets
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By NguyenNgocBinh, 2023"
    
  sidebar:
    logo: "images/nnb_hex.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://nguyenngocbinh.github.io/snippets
        text: "Nguyễn Ngọc Bình"
      - icon: github
        href: https://github.com/nguyenngocbinh/snippets
        text: "Snippet R, python, SQL, Stata"
      - icon: twitter
        href: https://twitter.com/nanabi88
        text: "nanabi88 Twitter"         

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - section: comparision/Index.md
        contents: 
          - comparision/plsql-db2.md
          - comparision/dplyr-pandas.md
          - comparision/ggplot2-matplotlib.md
      - section: python-snippet/Index.md
        contents: 
          - python-snippet/Environment.md
          - python-snippet/Graphs.md
          - python-snippet/slopegraph.ipynb
          - python-snippet/Modelling.md 
          - python-snippet/Statistics.md    
          - python-snippet/Code - optimize.md
          - python-snippet/Ultilities.md
          - python-snippet/REST_API.md
      - section: Crash-Course-Python/Exercise 1 - Python.ipynb
      - section: Crash-Course-Numpy/00-NumPy-Arrays.ipynb
        contents:
          - Crash-Course-Numpy/01-NumPy-Indexing-and-Selection.ipynb
          - Crash-Course-Numpy/02-NumPy-Operations.ipynb
          - Crash-Course-Numpy/03-NumPy-Exercises.ipynb
      - section: Crash-Course-Pandas/00-Intro-to-Pandas.ipynb
        contents: 
          - Crash-Course-Pandas/01-Series.ipynb
          - Crash-Course-Pandas/02-DataFrames.ipynb
          - Crash-Course-Pandas/03-Missing-Data.ipynb
          - Crash-Course-Pandas/04-Groupby.ipynb
          - Crash-Course-Pandas/05-Operations.ipynb
          - Crash-Course-Pandas/06-Data-Input-and-Output.ipynb
          - Crash-Course-Pandas/07-Pandas-Exercises-1.ipynb
          - Crash-Course-Pandas/09-Pandas-Exercises-2.ipynb      
      - section: Crash-Course-Matplotlib/Exercise 3 - Matplotlib.ipynb    
      - section: r-snippet/index.md
        contents: 
          - r-snippet/dplyr.md      
          - r-snippet/ggplot2.md
          - r-snippet/gganimate.md
          - r-snippet/treemap.md    
          - r-snippet/database.md
          - r-snippet/reticulate.md
          - r-snippet/file_folders.md   
          - r-snippet/DT.md    
          - r-snippet/create_package.md   
      - section: sqlserver-snippet/Index.qmd
        contents: 
          - sqlserver-snippet/README.md
          - sqlserver-snippet/permissions.md
          - sqlserver-snippet/synonym.md
      - section: machine-learning/transformer.md
        contents:
          - machine-learning/transformer.md


format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
